import { classifyChatMessage, type ChatRoute } from "./chatIntentRouter";

const cases: Array<{ text: string; route: ChatRoute }> = [
  { text: "У тебя красивый меч.", route: "dialogue" },
  { text: "Где купить кинжал?", route: "trade" },
  { text: "Я хочу продать лук.", route: "trade" },
  { text: "Покажи арбалет.", route: "dialogue" },
  { text: "У меня закончились стрелы.", route: "dialogue" },
  { text: "Мой меч сломан.", route: "dialogue" },
  { text: "Кузнец может починить дубину?", route: "dialogue" },
  { text: "Я рассказываю о прошлом бое.", route: "dialogue" },
  { text: "Я не хочу вступать в бой.", route: "dialogue" },
  { text: "Я не атакую торговца.", route: "dialogue" },
  { text: "Не буду применять заклинание.", route: "dialogue" },
  { text: "Покажи, как правильно ударить мечом.", route: "trainingRequest" },
  { text: "Учусь стрелять из лука.", route: "trainingRequest" },
  { text: "Тренируюсь на манекене.", route: "trainingRequest" },
  { text: "Я достаю меч.", route: "meleePreparation" },
  { text: "Я убираю кинжал.", route: "worldAction" },
  { text: "Навожу арбалет на мишень, но не стреляю.", route: "rangedPreparation" },
  { text: "Навожу арбалет на дверь.", route: "rangedPreparation" },
  { text: "Навожу лук на мишень.", route: "rangedPreparation" },
  { text: "Накладываю стрелу.", route: "rangedPreparation" },
  { text: "Беру лук в руки.", route: "rangedPreparation" },
  { text: "Поднимаю щит.", route: "meleePreparation" },
  { text: "Заряжаю арбалет.", route: "rangedPreparation" },
  { text: "Расскажи о заклинании Игнис.", route: "dialogue" },
  { text: "Я не произношу заклинание.", route: "dialogue" },
  { text: "Начинаю бой.", route: "startCombat" },
  { text: "Нападаю на разбойника.", route: "meleeCombat" },
  { text: "Атакую стражника.", route: "meleeCombat" },
  { text: "Бью его мечом.", route: "meleeCombat" },
  { text: "Бью разбойника кулаком.", route: "meleeCombat" },
  { text: "Пинаю разбойника в ногу.", route: "meleeCombat" },
  { text: "Толкаю разбойника щитом.", route: "meleeCombat" },
  { text: "Хватаю разбойника за руку.", route: "meleeCombat" },
  { text: "Колю копьём в корпус.", route: "meleeCombat" },
  { text: "Бью молотом по щиту.", route: "meleeCombat" },
  { text: "Колю кинжалом в корпус.", route: "meleeCombat" },
  { text: "Пытаюсь ударить дубиной.", route: "meleeCombat" },
  { text: "Стреляю в волка.", route: "rangedCombat" },
  { text: "Выпускаю стрелу в разбойника.", route: "rangedCombat" },
  { text: "Выпускаю болт в разбойника.", route: "rangedCombat" },
  { text: "Нажимаю на спуск арбалета и стреляю.", route: "rangedCombat" },
  { text: "Произношу Игнис Ланца Хостис.", route: "magic" },
  { text: "Игнис Ланца Хостис", route: "magic" },
  { text: "игнис ланца хостис", route: "magic" },
  { text: "«Игнис Ланца Хостис»", route: "magic" },
  { text: "Игнис, Ланца, Хостис!", route: "magic" },
  { text: "Произношу: Игнис Ланца Хостис.", route: "magic" },
  { text: "Что означает Игнис?", route: "dialogue" },
  { text: "Аркел рассказывал мне про Игнис Ланца.", route: "dialogue" },
  { text: "Я не произношу Игнис.", route: "dialogue" },
  { text: "Можно купить свиток Игнис?", route: "trade" },
  { text: "Колдую огненный шар в орка.", route: "magic" },
  { text: "Применяю заклинание света.", route: "magic" },
  { text: "Я видел, как маг произнес Игнис.", route: "dialogue" },
  { text: "Я рассказываю, как вчера атаковал разбойника.", route: "dialogue" },
  { text: "Убираю меч, чтобы не начинать драку.", route: "worldAction" },
  { text: "Сколько стоит арбалет?", route: "trade" },
  { text: "Не атакую его.", route: "dialogue" },
  { text: "Не стреляю.", route: "dialogue" },
  { text: "Не применяю заклинание.", route: "dialogue" },
  { text: "Не хочу начинать бой.", route: "dialogue" },
  { text: "Я не атакую первого разбойника, а стреляю во второго.", route: "rangedCombat" },
  { text: "Я спрашиваю Эдгара, как лучше колоть мечом.", route: "trainingRequest" },
  { text: "Я достаю меч и атакую стражника.", route: "meleeCombat" },
  { text: "Покупаю арбалет и спрашиваю, как им стрелять.", route: "trade" },
];

for (const testCase of cases) {
  const result = classifyChatMessage(testCase.text);

  if (result.route !== testCase.route) {
    throw new Error(`Expected "${testCase.text}" to route to ${testCase.route}, got ${result.route}`);
  }
}
